from dataclasses import dataclass
from typing import Any
from uuid import UUID
from datetime import datetime

from server.models.enums import Source


@dataclass
class Log:
    log_id: int | None              # Primary key. Generated by database
    session_id: UUID                # Forign key. Ties to parent session
    target_time: datetime | None
    client_time: datetime | None
    server_time: datetime
    source: Source
    target: str | None              # Tag to identify which interface log comes from
    event: str                  
    data: dict[str, Any] | None     # Any relevant additional data
