from dataclasses import dataclass
from uuid import UUID
from datetime import datetime

from .enums import SessionState


@dataclass
class Session:
    session_id: UUID            # Primary Key. Generated by backend
    subject_id: str             # Used for grouping sessions that belong to same user
    session_state: SessionState # Current state of the session
    created_at: datetime
    started_at: datetime | None
    ended_at: datetime | None